checks:
  file-lines:
    config:
      threshold: 320
  method-complexity:
    config:
      threshold: 100
  method-lines:
    enabled: true
    config:
      threshold: 300
  similar-code:
    enabled: true
    config:
      threshold: 65
exclude_patterns:
  - 'src/abis'
  - 'src/hooks'
