checks:
  file-lines:
    config:
      threshold: 250
  method-complexity:
    config:
      threshold: 15
  method-lines:
    enabled: true
    config:
      threshold: 140
  similar-code:
    enabled: true
    config:
      threshold: 4
exclude_patterns:
  - 'src/abis'
  - 'src/hooks'
